### ISSUE TITLE
How can i add  a 'cancel' button to KVNProgress

### ISSUE THREAD

**Issue by kyosold** [kevin-hirsch/KVNProgress#21]
i like this HUD, but i found a question, how can i add a cancel button??

**Comment by kevin-hirsch** [comment]
For now, there is no possibility to do this. You can:
- fork this repository to implement this by your side
- or you can use the new `tapBlock` property of the `KVNConfiguration` object to precise whatever action block you want to be executed when the HUD is tapped by the user. This is available since this commit 07a107b14d8cf5570bdec376703c0ac4b05c2fc8 and in the new Cocoapods version 1.2.7 (Example in the README.md) ;)
